#!/usr/bin/env python3
"""
API: Slack Webhook 推送
推送職位通知到 Slack 頻道
"""
import json
import os
import requests
from http.server import BaseHTTPRequestHandler


class handler(BaseHTTPRequestHandler):
    def do_POST(self):
        try:
            content_length = int(self.headers.get('Content-Length', 0))
            post_data = self.rfile.read(content_length).decode('utf-8')
            data = json.loads(post_data)

            # 取得 Slack Webhook URL
            webhook_url = os.environ.get('SLACK_WEBHOOK_URL', '')

            if not webhook_url:
                self.send_response(400)
                self.send_header('Content-Type', 'application/json')
                self.end_headers()
                self.wfile.write(json.dumps({
                    'success': False,
                    'error': 'Slack Webhook URL not configured'
                }).encode())
                return

            # 取得職位資料
            jobs = data.get('jobs', [])
            title = data.get('title', '🎯 AI Job Agent 推薦職位')

            if not jobs:
                self.send_response(400)
                self.send_header('Content-Type', 'application/json')
                self.end_headers()
                self.wfile.write(json.dumps({
                    'success': False,
                    'error': 'No jobs provided'
                }).encode())
                return

            # 建立 Slack 訊息格式（Block Kit）
            blocks = [
                {
                    "type": "header",
                    "text": {
                        "type": "plain_text",
                        "text": title,
                        "emoji": True
                    }
                },
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": f"找到 *{len(jobs)}* 個推薦職位（依匹配度排序）"
                    }
                },
                {"type": "divider"}
            ]

            # 加入職位卡片（Top 10）
            for i, job in enumerate(jobs[:10], 1):
                match_score = job.get('match_score', 0)
                job_title = job.get('title', 'Untitled')
                company = job.get('company', 'Unknown')
                location = job.get('location', 'Remote')
                url = job.get('url', '')

                # Emoji 根據匹配度
                emoji = '🔥' if match_score >= 85 else '⭐' if match_score >= 70 else '📌'

                # 匹配技能
                matched_skills = job.get('matched_skills', [])
                skills_text = f"\n✨ {', '.join(matched_skills[:3])}" if matched_skills else ""

                # 職位區塊
                job_block = {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": f"{emoji} *{i}. {job_title}*\n"
                                f"🏢 {company} · 📍 {location}\n"
                                f"🎯 匹配度：*{match_score}%*{skills_text}"
                    }
                }

                if url:
                    job_block["accessory"] = {
                        "type": "button",
                        "text": {
                            "type": "plain_text",
                            "text": "查看職位",
                            "emoji": True
                        },
                        "url": url,
                        "style": "primary" if match_score >= 85 else "default"
                    }

                blocks.append(job_block)

            # 分隔線
            blocks.append({"type": "divider"})

            # 頁尾
            blocks.append({
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": "_Generated by AI Job Agent v3.4.0_"
                    }
                ]
            })

            # 發送到 Slack
            payload = {
                "blocks": blocks,
                "text": title  # fallback text
            }

            response = requests.post(webhook_url, json=payload, timeout=10)
            response.raise_for_status()

            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.send_header('Access-Control-Allow-Origin', '*')
            self.end_headers()

            self.wfile.write(json.dumps({
                'success': True,
                'message': 'Successfully sent to Slack',
                'jobs_count': len(jobs)
            }).encode())

        except requests.exceptions.RequestException as e:
            self.send_response(500)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({
                'success': False,
                'error': f'Slack API error: {str(e)}'
            }).encode())

        except Exception as e:
            self.send_response(500)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({
                'success': False,
                'error': str(e)
            }).encode())

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        self.end_headers()
