#!/usr/bin/env python3
"""
API: Telegram Bot 推送
推送職位通知到 Telegram
"""
import json
import os
import requests
from http.server import BaseHTTPRequestHandler


class handler(BaseHTTPRequestHandler):
    def do_POST(self):
        try:
            content_length = int(self.headers.get('Content-Length', 0))
            post_data = self.rfile.read(content_length).decode('utf-8')
            data = json.loads(post_data)

            # 取得環境變數
            bot_token = os.environ.get('TELEGRAM_BOT_TOKEN', '')
            chat_id = os.environ.get('TELEGRAM_CHAT_ID', '')

            if not bot_token or not chat_id:
                self.send_response(400)
                self.send_header('Content-Type', 'application/json')
                self.end_headers()
                self.wfile.write(json.dumps({
                    'success': False,
                    'error': 'Telegram credentials not configured'
                }).encode())
                return

            # 取得職位資料
            jobs = data.get('jobs', [])
            title = data.get('title', '🎯 AI Job Agent 推薦職位')

            if not jobs:
                self.send_response(400)
                self.send_header('Content-Type', 'application/json')
                self.end_headers()
                self.wfile.write(json.dumps({
                    'success': False,
                    'error': 'No jobs provided'
                }).encode())
                return

            # 格式化訊息（Telegram Markdown）
            message = f"*{title}*\n\n"
            message += f"找到 *{len(jobs)}* 個推薦職位\n"
            message += "─" * 30 + "\n\n"

            for i, job in enumerate(jobs[:10], 1):  # 限制 10 筆（避免訊息過長）
                match_score = job.get('match_score', 0)
                job_title = job.get('title', 'Untitled')
                company = job.get('company', 'Unknown')
                location = job.get('location', 'Remote')
                url = job.get('url', '')

                # Emoji 根據匹配度
                emoji = '🔥' if match_score >= 85 else '⭐' if match_score >= 70 else '📌'

                message += f"{emoji} *{i}. {job_title}*\n"
                message += f"🏢 {company} · 📍 {location}\n"
                message += f"🎯 匹配度：*{match_score}%*\n"

                # 匹配技能
                matched_skills = job.get('matched_skills', [])
                if matched_skills:
                    message += f"✨ {', '.join(matched_skills[:3])}\n"

                if url:
                    message += f"[→ 查看職位]({url})\n"

                message += "\n"

            message += "─" * 30 + "\n"
            message += "_Generated by AI Job Agent_"

            # 發送到 Telegram
            telegram_url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
            payload = {
                'chat_id': chat_id,
                'text': message,
                'parse_mode': 'Markdown',
                'disable_web_page_preview': True
            }

            response = requests.post(telegram_url, json=payload, timeout=10)
            response.raise_for_status()

            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.send_header('Access-Control-Allow-Origin', '*')
            self.end_headers()

            self.wfile.write(json.dumps({
                'success': True,
                'message': f'Successfully sent to Telegram (chat_id: {chat_id})',
                'jobs_count': len(jobs)
            }).encode())

        except requests.exceptions.RequestException as e:
            self.send_response(500)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({
                'success': False,
                'error': f'Telegram API error: {str(e)}'
            }).encode())

        except Exception as e:
            self.send_response(500)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({
                'success': False,
                'error': str(e)
            }).encode())

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        self.end_headers()
